# Generated by Django 4.1.5 on 2023-01-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='join',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.TextField(),
        ),
    ]
